[phases.setup]
aptPkgs = [
  "curl",
  "unzip"
]
cmds = [
  "apt update",
  "apt upgrade -y",
  "curl -fsSL https://bun.sh/install | bash"
]

[phases.install]
cmds = [ "$HOME/.bun/bin/bun install" ]

[phases.build]
cmds = [ "$HOME/.bun/bin/bun run build" ]

[start]
cmd = "$HOME/.bun/bin/bun run start"
