name = "lunacea-portfolio"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"
database_name = "lunacea_db"
# TODO: CloudflareダッシュボードでD1を作成後、IDに置換
database_id = "REPLACE_WITH_D1_ID"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "lunacea-assets"
