name = "lunacea-portfolio"
compatibility_date = "2025-08-23"

[[d1_databases]]
binding = "DB"
database_name = "lunacea_portfolio"
database_id = "5e0f867b-37ef-442c-a6b5-137ae8bbb0d6"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "lunacea-portfolio"
