name: Security Scan

on:
  workflow_call:
    inputs:
      scan-type:
        description: 'Type of scan to perform'
        required: false
        type: string
        default: 'fs'
      severity:
        description: 'Minimum severity level'
        required: false
        type: string
        default: 'CRITICAL,HIGH'
      image-ref:
        description: 'Container image reference for image scanning'
        required: false
        type: string
    outputs:
      vulnerabilities-found:
        description: 'Whether vulnerabilities were found'
        value: ${{ jobs.security-scan.outputs.vulnerabilities-found }}
      scan-results:
        description: 'Path to scan results file'
        value: ${{ jobs.security-scan.outputs.scan-results }}

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    outputs:
      vulnerabilities-found: ${{ steps.trivy.outcome == 'failure' }}
      scan-results: ${{ steps.trivy.outputs.output }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: ${{ inputs.scan-type }}
          scan-ref: ${{ inputs.image-ref || '.' }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.severity }}
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Fail on high severity vulnerabilities
        if: failure()
        run: |
          echo "❌ High severity vulnerabilities detected. Please review and fix them."
          echo "Scan results: ${{ steps.trivy.outputs.output }}"
          exit 1
      
      - name: Upload security scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results-${{ github.sha }}
          path: trivy-results.sarif
          retention-days: 30
