name: Setup Bun Environment

on:
  workflow_call:
    inputs:
      cache-key:
        description: 'Cache key suffix for dependencies'
        required: false
        type: string
        default: 'default'
      install-command:
        description: 'Install command to run'
        required: false
        type: string
        default: 'bun install --frozen-lockfile'
    outputs:
      cache-hit:
        description: 'Whether cache was hit'
        value: ${{ jobs.setup.outputs.cache-hit }}

jobs:
  setup:
    name: Setup Bun
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ inputs.cache-key }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ inputs.cache-key }}-
            ${{ runner.os }}-bun-
      
      - name: Install dependencies
        run: ${{ inputs.install-command }}